### PR TITLE
Added package neovim -- This makes editor accessible via `nix run

### LINKED ISSUE #16: Add a flake app for running our neovim config
`nix run github:juspay/nix-dev-home#neovim` should run neovim with the config in this repo, without depending on any of user's dotfiles or local $HOME cache.

cf. https://old.reddit.com/r/NixOS/comments/1aulb75/easy_neovim_with_configuration_and_runnable_with/

### PR DESCRIPTION
**Pull request by niksingh710**
Tries to fix #16 

@srid Did a dirty commit where I am importing `standalone` config in `home-manager` module.

### CODE REVIEW

**Review by srid — CHANGES_REQUESTED** [review]
Just needs two changes:

- Merge latest `main` so d201da2 enables minimal diff of this PR.
- Avoid `flake.nix` changes, by decoupling the package onto a `./nix/modules/flake-parts/neovim.nix` file, such that it also keeps the neovim-inclusion feature work in https://omnix.page/om/init.html

**Comment by srid** [comment]
Note: no need to `git rebase`, since this PR will be squash-merged anyway.

**Review by niksingh710 — COMMENTED** [review]
https://github.com/juspay/nix-dev-home/pull/76/commits/a4d5e4b379d959c8c6e83728a4f5680b9aa7fa73 addresses the changes

**Review by srid — APPROVED** [review]
Works great.

**Comment by srid** [comment]
https://x.com/nixos_asia/status/1834679190815400422

**Pull request merged**
